In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [4]:
dataset = pd.read_csv("Position_Salaries.csv")
X = dataset.iloc[:, -1].values
y = dataset.iloc[:, 1:-1].values
print(X)
print(y)

[  45000   50000   60000   80000  110000  150000  200000  300000  500000
 1000000]
[[ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]]


In [5]:
X = X.reshape(len(X), 1)
print(X)

[[  45000]
 [  50000]
 [  60000]
 [  80000]
 [ 110000]
 [ 150000]
 [ 200000]
 [ 300000]
 [ 500000]
 [1000000]]


In [14]:
from sklearn.preprocessing import StandardScaler
sc_X = StandardScaler()
sc_y = StandardScaler()
X = sc_X.fit_transform(X)
y = sc_y.fit_transform(y)

print(X)
print(y)

[[-0.72004253]
 [-0.70243757]
 [-0.66722767]
 [-0.59680786]
 [-0.49117815]
 [-0.35033854]
 [-0.17428902]
 [ 0.17781001]
 [ 0.88200808]
 [ 2.64250325]]
[[-1.5666989 ]
 [-1.21854359]
 [-0.87038828]
 [-0.52223297]
 [-0.17407766]
 [ 0.17407766]
 [ 0.52223297]
 [ 0.87038828]
 [ 1.21854359]
 [ 1.5666989 ]]


In [15]:
from sklearn.svm import SVR
regressor = SVR(kernel="rbf")
regressor.fit(X, y)

/home/vikasrai19/.local/lib/python3.6/site-packages/sklearn/utils/validation.py:63: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(*args, **kwargs)


SVR()

In [19]:
sc_y.inverse_transform(regressor.predict(sc_X.transform([[1000000]])))

array([9.7125803])

In [23]:
exp_salary = float(input("Enter your expected salary"))
print(f"Your Position level must be minimum of {sc_y.inverse_transform(regressor.predict(sc_X.transform([[exp_salary]])))} to attain a salary of {exp_salary}")

Your Position level must be minimum of [9.7125803] to attain a salary of 1000000.0
